name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (if needed for static site generators like Next.js)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (if applicable)
        run: npm install

      - name: Build the site (adjust this step for your framework)
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./index  # Replace this with the folder containing your built site
